; PlatformIO CI configuration for compiling PotIO examples across common
; Little Man Builds Arduino targets.

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+

[env:uno]
platform = atmelavr
board = uno

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560

[env:nano_every]
platform = atmelmegaavr
board = nano_every

[env:mkrzero]
platform = atmelsam
board = mkrzero

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2

[env:pico]
platform = raspberrypi
board = pico

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8

[env:teensy41]
platform = teensy
board = teensy41
